In [1]:
import numpy as np

In [7]:
# 011 다음과 같이 2차원 ndarray 객체를 정의하세요.
data = [
    [0, 1, 2],
    [3, 4, 5]
]

arr = np.array(data)    # 방법 1
# arr

# np.array([[0, 1, 2], [3, 4, 5]])  # 방법 2

# np.arange(6).reshape(2, 3)  # 방법 3

In [15]:
# 012 ones : 1이 20개 저장된아래의 ndarray 객체를 만들어 보세요
data = [1] * 20

np.array(data)  # 방법 1

np.ones(20, dtype=int)  # 방법 2

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [16]:
# 013 ones : 4행 5열로 저장된 아래의 ndarray 객체를 만들어 보세요.
np.ones(20, dtype=int).reshape(4, 5)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [20]:
# 014 ones : 255로 채워진 10X10 크기의 ndarray 객체를 생성하세요.
arr = np.ones(100, dtype=int).reshape(10, 10)
arr = arr * 255
arr

array([[255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255]])

In [26]:
# 015 zeros : 3x4 (행x열) 크기의 0으로 채워진 배열을 생성해보세요
# arr = np.zeros(12, dtype=int).reshape(3, 4)
arr = np.zeros((3, 4), dtype=int)
arr

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [29]:
# 016 dtype : [1, 2, 3]을 np.int32 타입의 ndarray 배열로 생성하세요.
data = [1, 2, 3]
arr = np.ndarray(data, dtype=np.int32)
data

[1, 2, 3]

In [34]:
# 017 dtype : 다음 배열의 데이터 타입을 확인해보세요
arr = np.array([1,2,3])
arr.dtype

dtype('int32')

In [35]:
# 018 dtype : 다음 배열의 데이터 타입을 확인해보세요
arr = np.array(['1', '2', '3'])
arr.dtype

dtype('<U1')

In [36]:
# 019 dtype : np.int16 타입으로 변경
arr = np.array([1, 2, 3])
arr.astype(np.int16)

array([1, 2, 3], dtype=int16)

In [38]:
# 020 데이터 타입 : 300이 44로 출력되는 이유
a = np.array([255, 300, 128], dtype=np.uint8)
a

# 데이터 타입이 int8로 설정되었고, 1바이트를 넘어가는 데이터가 잘림

array([255,  44, 128], dtype=uint8)