In [1]:
import numpy as np

In [5]:
# 021 astype : arr 배열 float 64 -> np.int32
arr = np.array([1.1, 2.1, 3.1])
arr = arr.astype(np.int32)
arr.dtype

dtype('int32')

In [11]:
# 022 linspace : 0 ~ 10 사이를 구간 20개의 포인트로 분할한 결과 ndarray로 표현
np.linspace(0, 10, 20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [15]:
# 023 로우 인덱싱 : 다음 ndarray에서 마지막 로우 ([6, 7, 8])을 출력
arr = np.arange(9).reshape(3, 3)
arr[2]
arr[-1]

array([6, 7, 8])

In [17]:
# 024 컬럼 인덱싱 : 다음 ndarray에서 두 번째 컬럼([1, 4, 7])을 출력
arr = np.arange(9).reshape(3, 3)
arr[:, 1]

array([1, 4, 7])

In [20]:
# 025 데이터 인덱싱 : 다음 ndarray에서 17을 선택하는 코드 작성
arr = np.arange(25).reshape(5, 5)
arr[3][2]
arr[3, 2]

17

In [26]:
# 026 슬라이싱 : [1 3]을 슬라이싱하는 코드를 작성
arr = np.arange(5)
arr[1::2]   # 1위치에서 2 단위로 가져오기
arr[[1, 3]]

array([1, 3])

In [33]:
# 027 슬라이싱 : [6 7 8 9]를 슬라이싱 하는 코드
arr = np.arange(25).reshape(5, 5)
arr[1, 1:]

array([6, 7, 8, 9])

In [37]:
# 028 슬라이싱 : 첫번째와 두번째 컬럼 슬라이싱하는 코드 작성
arr = np.arange(25).reshape(5, 5)
arr[:, : 2]

array([[ 0,  1],
       [ 5,  6],
       [10, 11],
       [15, 16],
       [20, 21]])

In [41]:
# 029 슬라이싱 : 6, 7, 11, 12를 2x2 ndarray로 슬라이싱하는 코드
arr = np.arange(25).reshape(5, 5)
arr[1:3, 1:3]

array([[ 6,  7],
       [11, 12]])

In [68]:
# 030 슬라이싱 : 0, 3, 20, 23를 2x2 ndarray로 슬라이싱하는 코드
arr = np.arange(25).reshape(5, 5)
arr[[0, -1], 0::3]

array([[ 0,  3],
       [20, 23]])