In [1]:
import numpy as np

In [6]:
# 041 조건에 맞는 원소값 출력 : 음수 출력
arr = np.array([-1, 2, -3, 4])
arr[arr<0]

cond = arr<0
arr[cond]

array([-1, -3])

In [10]:
# 042 조건에 맞는 원소값 변경
arr = np.array([-1, 2, -3, 4])
arr[arr < 0] = 0
arr

array([0, 2, 0, 4])

In [19]:
# 043 조건에 맞는 원소값 변경
arr = np.array([-1, 2, -3, 4])
cond = arr<0
arr[cond] = -arr[cond]
arr

arr[arr<0] = -arr[arr<0]
arr

abs(arr)

array([1, 2, 3, 4])

In [26]:
# 044 조건에 맞는 원소값 변경 : 객체에서 양수 혹은 0이면 10을 더하고 음수는 10을 뺀다.
arr = np.array([-1, 2, -3, 4])

# arr[arr>=0] = arr[arr>=0] + 10
# arr[arr<0] = arr[arr<0] - 10
# arr

np.where(arr>=0, arr+10, arr-10)


array([-11,  12, -13,  14])

In [31]:
# 045 shuffle : numpy random 모듈의 shuffle 함수 사용해서 입력 리스트 원소 랜덤으로 섞기
arr = [1, 2, 3, 4, 5]
np.random.shuffle(arr)
arr

[3, 2, 4, 1, 5]

In [36]:
# 046 argmin : 넘파이 배열에서 최소값의 인덱스
arr = np.array([1, 2, 3, 4, 5])
arr.argmin()

0

In [38]:
# 047 argmax : 최댓값의 인덱스
arr = np.array([1, 2, 3, 4, 5])
arr.argmax()

4

In [46]:
# 048 정렬 : 오름차순 정렬
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
# arr.sort()
# arr
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [49]:
# 049 numpy.vstack : vstack 함수를 사용해 2차원 배열을 생성
arr1 = np.array([1, 2])
arr2 = np.array([3, 4])

np.vstack((arr1, arr2))

array([[1, 2],
       [3, 4]])

In [50]:
# 050 flatten : flatten 메서드 사용해 다음 배열 1차원 배열로 변경
arr = np.array([ [1, 2], [3, 4] ])
arr.flatten()

array([1, 2, 3, 4])