In [1]:
# 001 넘파이 임포트
import numpy as np

In [11]:
# 002 ndarray : 리스트를 넘파이의 ndarray 객체로 변환
data = [1,2,3]

np.array(data)

array([1, 2, 3])

In [15]:
# 003 arange : 0부터 99까지의 정수가 저장된 ndarray 객체를 만들어 보세요
np.arange(100)


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [26]:
# 004 arange : 구구단 3단의 결과가 저장된 ndarray 객체를 만들어 보세요
arr = np.arange(1, 10) * 3
arr

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27])

In [29]:
# 005 arange : 1000보다 작은 짝수가 저장된 ndarray 객체를 만들어 보세요
arr = np.arange(2, 1000, 2)
arr

In [31]:
# 006 실수 range : 0부터 1까지 0.1 간격으로 구성된 ndarray를 생성해보세요. 1은 포함되지 않습니다.
arr = np.arange(0, 1, 0.1)
arr

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [36]:
# 007 reshape : 리스트에 6개의 데이터를 2행 3열의 ndarray로 변환하세요
data = [0, 1, 2, 3, 4, 5]

data = np.array(data)
data = data.reshape([2, 3])
data

array([[0, 1, 2],
       [3, 4, 5]])

In [45]:
# 008 reshape : 다음의 2차원 ndarray 1차원 ndarray로 변환하세요
arr = np.array([
    [0, 1, 2],
    [3, 4, 5]
])

# 둘 중에 하나 쓰면 됨.
# arr.reshape([6])
arr.flatten()

array([0, 1, 2, 3, 4, 5])

In [47]:
# 009 reshape : 주어진 ndarray를 다음과 같이 변경해 보세요
arr = np.arange(3)
arr.reshape(3, 1)

array([[0],
       [1],
       [2]])

In [49]:
# 010 에러의 원인 : 에러의 원인을 설명하세요
np.arange(6).reshape(2, 4)

# 사이즈 6의 개체를 2,4 형태에 모두 넣을수 없음.

ValueError: cannot reshape array of size 6 into shape (2,4)