In [2]:
import numpy as np

In [7]:
# 031 ndarray 곱셈 : 전체 데이터에 10을 곱함
data = [1, 2, 3]
result = np.array(data) * 10
result

array([10, 20, 30])

In [9]:
# 032 ndarray 제곱 : 전체 데이터에 제곱
data = [1, 2, 3]
result = np.array(data) ** 2
result

array([1, 4, 9], dtype=int32)

In [12]:
# 033 ndarray 루트 : 전체 데이터에 루트 적용
data = [1, 2, 3]
result = np.array(data) ** 0.5
result

array([1.        , 1.41421356, 1.73205081])

In [21]:
# 034 ndarray 컬럼 평균 : 과목별 평균 점수 출력
score = np.array([
    [10, 20],
    [14, 16]
])

score.mean(axis=0)

array([12., 18.])

In [22]:
# 035 ndarray 로우 표준편차 : 표준편차 출력
score = np.array([
    [10, 20],  # 중간고사
    [14, 16]   # 기말고사
])
score.std(axis=1)

array([5., 1.])

In [27]:
# 036 행렬곱 : 두 행렬의 곱셈결과
a = np.arange(4).reshape(2, 2)
b = np.arange(1, 5).reshape(2, 2)
a*b

array([[ 0,  2],
       [ 6, 12]])

In [31]:
# 037 전치행렬 : 행과 위치 바꾸기
arr = np.arange(9).reshape(3, 3)
print(arr.T)
print(arr.transpose())

[[0 3 6]
 [1 4 7]
 [2 5 8]]
[[0 3 6]
 [1 4 7]
 [2 5 8]]


In [34]:
# 038 짝수 배열 : 짝수 값만 추출
arr = np.arange(10)
arr[0::2]

array([0, 2, 4, 6, 8])

In [36]:
# 039 홀수 배열 : 홀수 값만 추출
arr = np.arange(10)
arr[1::2]

array([1, 3, 5, 7, 9])

In [49]:
# 040 여러 조건 : 다음 배열에서3보다 크고 7보다 작은 수만 추출
arr = np.arange(10)
arr[np.logical_and(arr>3, arr<7)]
arr[(arr>3) & (arr<7)]

array([4, 5, 6])